# AntChem Asset Map — maps material/intermediate/equipment IDs to sprite paths
# All sprites procedurally generated by tools/generate_all.py
extends RefCounted

const MATERIAL_ICONS = {
	"sulfur":       "res://assets/mat_sulfur.png",
	"saltpeter":    "res://assets/mat_saltpeter.png",
	"charcoal":     "res://assets/mat_charcoal.png",
	"clay":         "res://assets/mat_clay.png",
	"iron_rust":    "res://assets/mat_iron_rust.png",
	"limestone":    "res://assets/mat_limestone.png",
	"diatomite":    "res://assets/mat_diatomite.png",
	"formic_acid":  "res://assets/mat_formic_acid.png",
	"beeswax":      "res://assets/mat_beeswax.png",
	"resin":        "res://assets/mat_resin.png",
	"fat":          "res://assets/mat_fat.png",
	"plant_ash":    "res://assets/mat_plant_ash.png",
	"rot_soil":     "res://assets/mat_rot_soil.png",
	"ammonium":     "res://assets/mat_ammonium.png",
	"fireant_venom":"res://assets/mat_fireant_venom.png",
	"lead_powder":  "res://assets/mat_lead_powder.png",
}

const EQUIPMENT_ICONS = {
	"mortar_stone":      "res://assets/equip_mortar_stone.png",
	"mortar_graded":     "res://assets/equip_mortar_graded.png",
	"mortar_precision":  "res://assets/equip_mortar_precision.png",
	"firefly_lamp":      "res://assets/equip_firefly_lamp.png",
	"crucible_thermo":   "res://assets/equip_crucible_thermo.png",
	"furnace":           "res://assets/equip_furnace.png",
	"still":             "res://assets/equip_still.png",
	"acid_bench":        "res://assets/equip_acid_bench.png",
	"nut_crucible":      "res://assets/equip_nut_crucible.png",
	"soak_trough":       "res://assets/equip_soak_trough.png",
	"press_hydraulic":   "res://assets/equip_press_hydraulic.png",
	"cure_oven":         "res://assets/equip_cure_oven.png",
	"det_testbench":     "res://assets/equip_det_testbench.png",
	"stone_trough":      "res://assets/equip_stone_trough.png",
}

const INTERMEDIATE_ICONS = {
	"aromatic_oil":    "res://assets/inter_aromatic_oil.png",
	"carbon_fiber":    "res://assets/inter_carbon_fiber.png",
	"nitrating_acid":  "res://assets/inter_nitrating_acid.png",
	"stabilizing_wax": "res://assets/inter_stabilizing_wax.png",
}

const SCENE_SPRITES = {
	"cave_wall_tile":   "res://assets/cave_wall_tile.png",
	"firefly_glow":     "res://assets/firefly_glow.png",
	"explosive_placed": "res://assets/explosive_placed.png",
	"ant_idle":         "res://assets/ant_idle_",
	"ant_walk":         "res://assets/ant_walk_",
	"particle_smoke":   "res://assets/particle_smoke.png",
	"particle_fire":    "res://assets/particle_fire.png",
	"particle_spark":   "res://assets/particle_spark.png",
	"ui_node_known":    "res://assets/ui_node_known_explosive.png",
	"ui_node_inter":    "res://assets/ui_node_intermediate.png",
	"ui_node_locked":   "res://assets/ui_node_locked.png",
	"ui_naming_bg":     "res://assets/ui_naming_bg.png",
}

const BLOCK_SPRITES = {
	"soil_32":  "res://assets/brick_soil_32x32.png",
	"stone_32": "res://assets/brick_stone_32x32.png",
	"clay_32":  "res://assets/brick_clay_32x32.png",
	"soil_64":  "res://assets/brick_soil_64x32.png",
	"stone_64": "res://assets/brick_stone_64x32.png",
	"rust_64":  "res://assets/brick_rust_64x32.png",
	"clay_64":  "res://assets/brick_clay_64x32.png",
}

static func get_material_icon(mat_id: String) -> String:
	return MATERIAL_ICONS.get(mat_id, "")

static func get_equipment_icon(eq_id: String) -> String:
	return EQUIPMENT_ICONS.get(eq_id, "")

static func get_intermediate_icon(inter_id: String) -> String:
	return INTERMEDIATE_ICONS.get(inter_id, "")

static func get_scene_sprite(key: String) -> String:
	return SCENE_SPRITES.get(key, "")

static func get_block_sprite(key: String) -> String:
	return BLOCK_SPRITES.get(key, "")
